### PR TITLE
Update dependent omniauth to latest

### LINKED ISSUE #46: needs an update on omniauth dependency
currently it is dependent on omniauth version `~1.0` but the omniauth version `1.9.1` has reported high severity CVE and we need to update the omniauth version to `~2.0`

### PR DESCRIPTION
**Pull request by SathishAchilles**
Fixes #46

### CODE REVIEW

**Comment by Watanabe-SmaMedia** [comment]
@omniauth Is it possible for someone to merge this PR?

**Comment by joeytheman** [comment]
@BobbyMcWho @bufferoverflow - Would you be able to merge this PR?

**Comment by BobbyMcWho** [comment]
I can merge, but I don't think I have release rights on rubygems to cut a release

**Comment by joeytheman** [comment]
@BobbyMcWho - that's fine. We can reference that commit SHA until then.

**Pull request merged**
